import '@/styles/reset.scss';

import type { Metadata } from 'next';

import { sen } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Client Blog App',
  description: 'Generated by create next app',
};

interface LayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

const RootLayout: React.FC<LayoutProps> = ({ children, params }) => (
  <html lang={params.locale}>
    <body className={sen.className}>{children}</body>
  </html>
);

export default RootLayout;
